### ISSUE TITLE
Concordance 1.3 and libbz2-1.dll

### ISSUE THREAD

**Issue by jchamlin** [jaymzh/concordance#23]
The 1.3 Windows installer built last year doesn't install a working version. I see this pull #19 was merged in that fixes the problem, but a new release has not been released since then. I downloaded the 1.3a installer linked from here https://sourceforge.net/p/concordance/mailman/message/36475537/.

Can we get a new release?

**Comment by jaymzh** [comment]
Ah yeah, we should indeed get a release out the door. I'll do that next week after the Halloween Shenanigans.

**Comment by jaymzh** [comment]
New version has been released. Just need some windows binaries, which I'm hoping @swt2c will be nice enough to build.

**Comment by jaymzh** [comment]
Windows installer added to the 1.4 release.
