### ISSUE TITLE
Volume on Harmony 655

### ISSUE THREAD

**Issue by RedSoxFan04** [jaymzh/concordance#28]
I bought a Harmony 665 a few days ago to replace my failing Harmony 350 from a couple years ago. I set it up on my MacBook Pro, but I ran into a problem - it turns out that the version of the Harmony software on my MacBook is too old for this remote. My MacBook is from 2011 and it can only go as far as macOS 10.13 (High Sierra), but the new Harmony software needs macOS Catalina (10.15) or later.

The version of the Harmony software on my MacBook was able to set up the remote fairly well, but with one glaring omission - volume controls. Towards the beginning of the setup process, it should have asked me which device should be used for volume control (i.e. TV, receiver), but it didn't. I looked into the matter and there's supposed to be another way to go about it, but that didn't work either. 

I much prefer Linux and Congruity. Unfortunately, Congruity is missing a couple things, so I sometimes use Logitech's software. 

I tried fixing this volume issue in Congruity, but no luck.

**Comment by swt2c** [comment]
Recommend reporting this at Congruity's Sourceforge or https://github.com/congruity/congruity
