### ISSUE TITLE
Does this software still work?

### ISSUE THREAD

**Issue by robross0606** [jaymzh/concordance#29]
I'm trying to use this to program my Harmony One+ because the MyHarmony simply stinks.  However, I'm baffled about how to actually set up and use it.  The referenced website looks like it may no longer be functional.  I cannot log in or use it from a browser, even with the recommend Chrome extension.  Does this software still work?  What am I doing wrong here?

**Comment by swt2c** [comment]
If you have a remote that uses MyHarmony.com, it won't work with members.harmonyremote.com.  You need to use 'mhgui' from the congruity package: https://github.com/congruity/congruity

**Comment by robross0606** [comment]
Thanks for responding so quickly.  Trying to set up congruity, but this is a Windows system.  The instructions imply this might not work on a Windows system even though it is mostly python.  Will Congruity work on Windows?

**Comment by swt2c** [comment]
To be perfectly honest, I'm not sure if anyone has ever tried it on Windows.  However, it should in theory work.  Feel free to give it a try and report any bugs, which I'll try to fix.

**Comment by robross0606** [comment]
Would you prefer I move this convo over to the Congruity project?

**Comment by swt2c** [comment]
Yes.  Congruity relies on Concordance, but Concordance I've definitely tested on Windows, although not recently.

**Comment by jaymzh** [comment]
We try to keep these projects cross-platform, however the primary purpose of them is the platforms where the official software doesn't work (mostly Linux). If you're on Windows, you're welcome to use our software of course, but just for the record you don't _need_ to, the official software will work well and likely have more features (we are, by definition, always going to trail them as new stuff has to come out before we can even start trying to implement it).

**Comment by jaymzh** [comment]
(closing, if you're having issues on congruity, file it on that project. thanks!)
