### ISSUE TITLE
MH website not working anymore?

### ISSUE THREAD

**Issue by vincentbernat** [jaymzh/concordance#34]
Hey,

It seems http://members.harmonyremote.com/EasyZapper/ is now broken. I get the first page, but clicking on "Next" lead to a 404 error. Fortunately, I was able to bypass it with http://members.harmonyremote.com/EasyZapper/New/ProcLogin/Start.asp?BrowserIsChecked=True.

**Comment by ondrej-zary** [comment]
Great, this helped me. I can now login and configure everything. But updating remote fails - website refreshes an empty page infinitely. Seems that the data from Congruity or Concordance did not reach the website.

Wireshark shows that the web server replies with "301 Moved Permanently" - redirects to HTTPS. Concordance does not seem to understand it.

**Comment by ondrej-zary** [comment]
Quick workaround: redirect the connection to localhost and proxy it as HTTPS. This works in Debian:
1. apt install nginx-light
2. edit /etc/nginx/sites-enabled/default -in "location /" block:
add "proxy_pass https://members.harmonyremote.com;"
remove (or comment-out) "try_files $uri $uri/ =404;"
3. /etc/init.d/nginx restart
4. /sbin/iptables -t nat -A OUTPUT -p tcp -d 52.44.86.125 --dport 80 -j DNAT --to-destination 127.0.0.1:80

I've updated my Harmony 525!

**Comment by swt2c** [comment]
I can confirm this.  concordance unfortunately needs to start speaking SSL now.  :(  I'm working on a fix.
