### ISSUE TITLE
https://members.harmonyremote.com/EasyZapper/UserHome.asp still functional?

### ISSUE THREAD

**Issue by brianjmurrell** [jaymzh/concordance#43]
I can log in to https://members.harmonyremote.com/EasyZapper/UserHome.asp with my account and see my devices, etc. but as soon as I click on [Add a Device](https://members.harmonyremote.com/EasyZapper/WizardNewDevice/NewDevice_LimitedDevices.asp) I am taken to a **Software Update Available** page with just a _Next_ button that goes to a dead link.

Same for [Remove a Device](https://members.harmonyremote.com/EasyZapper/New/Main.asp?WebProcessAction=Start&ReturnUrl=%2FEasyZapper%2FUserHome%2Easp&ClassId=PrSetupDevices%2EProcRemoveDevice&RelativePath=ProcSetupDevices%2F).

Anyone able to use either of these functions on this website now?

**Comment by brianjmurrell** [comment]
Actually clicking any/everything leads to that **Software Update Available**.  Is this their way of telling their users and software to upgrade and use a new web-service and that the https://members.harmonyremote.com/ is no longer functional?

**Comment by swt2c** [comment]
Did you try this link?  https://members.harmonyremote.com/EasyZapper/New/ProcLogin/Start.asp?BrowserIsChecked=True

I was able to Add a Device (although I didn't go all the way through it).

**Comment by jaymzh** [comment]
@brianjmurrell - where'd you get that URL? The URL in our [README](https://github.com/jaymzh/concordance/blob/master/README.md) is up-to-date.

**Comment by brianjmurrell** [comment]
I did some cookie clearing and it seems to at least let me update existing activities.  But I cannot get anything to happen after running the connectivity test.  Firefox just sits a blank window refreshing.  I am seeing in the FF console:

```
The resource from “https://members.harmonyremote.com/EasyZapper/styles-logi.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by swt2c** [comment]
Like I asked in the other issue, are you running the latest concordance from git master branch?

**Comment by brianjmurrell** [comment]
I am using the package included in Fedora 35 which appears to be:

https://github.com/jaymzh/concordance/releases/download/v1.4/concordance-1.4.tar.bz2

That's the latest release at https://github.com/jaymzh/concordance/releases.

**Comment by swt2c** [comment]
That release won't work.  You need to build from git unfortunately.

@jaymzh can we get a new release, please.

**Comment by brianjmurrell** [comment]
> @jaymzh can we get a new release, please.

+1

Then I can open a ticket for Fedora to be updated.  In the meanwhile I will build a new package here.

**Comment by jaymzh** [comment]
yeah I'll try to get that done today

**Comment by jaymzh** [comment]
https://github.com/jaymzh/concordance/pull/45 will prep the release, waiting for tests to pass, then will tag and release.

**Comment by brianjmurrell** [comment]
Confirming that master does fix my problems.

**Comment by brianjmurrell** [comment]
Hrm Add/Remove device still takes me back to that **Software Update Available** page.  :-(

**Comment by jaymzh** [comment]
OK, 1.5 is released. @swt2c - would you be so kind as to provide windows binaries?

**Comment by swt2c** [comment]
Aha, @jaymzh my past self knew you would ask for that and so I configured GitHub CI to produce them automatically.  :-)  You can get them here, see Artifacts:
https://github.com/jaymzh/concordance/actions/runs/2235497842

**Comment by brianjmurrell** [comment]
I guess the problem was that I had the max. number of devices added for my remote.

**Comment by jaymzh** [comment]
Doh, I knew that @swt2c - updated ReleaseChecklist to reflect that. Thanks!

**Comment by jaymzh** [comment]
@brianjmurrell - sounds like your issue is resolved, I'm going to close this.
