### ISSUE TITLE
concordance-1.5-installer.exe - can't run on windows 

### ISSUE THREAD

**Issue by tristelune** [jaymzh/concordance#46]
Hello

the installer of the 1.5 version cannot run on windows look like the file is corrupted/incomplet.

once downloaded the file does not show the setup icon like the previous version installation file.

Then when trying to run it with admin right we end with an error cannot found file "file_path"\concordance-1.5-installer.exe

And the setup does not start.

If you can upload again the file to correct the issue.

Thanks

**Comment by jaymzh** [comment]
Calling @swt2c ...

**Comment by swt2c** [comment]
@jaymzh the file you posted is a .zip file that contains the .exe (I guess GitHub zips up the artifacts).  So, either unzip it and repost, or rename it to .zip.

**Comment by jaymzh** [comment]
Doh! Thanks.

Fixed.
