### ISSUE TITLE
members.harmony.com is gone

### ISSUE THREAD

**Issue by ghost** [jaymzh/concordance#9]
The website at http://members.harmonyremote.com contains a generic IIS page, as if the entire members portal has been blown away.

The new website https://support.myharmony.com insist that you must install their app for Windows/Mac, which they will not even allow download using a Linux browser, so I haven't tried using wine yet.

Is this a Concordance killer? Has anyone found a way around it?

**Comment by poirier** [comment]
Try going directly to http://members.harmonyremote.com/EasyZapper/.  That still works for me.

**Comment by swt2c** [comment]
Yep, we noted that in https://github.com/jaymzh/concordance/blob/master/README.md
